### ISSUE TITLE
How to get a kaggle logo in the social media links section(besides the profile image)

### ISSUE THREAD

**Issue by soumya997** [soumik12345/soumik12345.github.io#1]
Sorry to create this issue.
I find this portfolio simple but very good, so I cloned it.
Just one query, **How to get a kaggle logo in the social media links section(besides the profile image)**.
I tried to do that by using as per [this](https://github.com/FortAwesome/Font-Awesome/issues/4363#issuecomment-356445786)
```css
.fa-font:before {
  font-family: roboto;
  color: #429bf4;
  font-size: 1.2em;
  content: "K";  
}
```

in the all.css file, and used in the HTML file,
```html
<i class="fa fa-font"></i>
```

but it did not help. Its looking like this,
<img src="https://i.imgur.com/TF1l1X0.jpg" width="700">

Any solution on how can I fix that?
